myconcert/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('subs.urls')),
    path('admin/', admin.site.urls),
]

subs/urls.py
from .forms import UserLoginForm
from django.urls import path, include
from django.contrib.auth import views
from .views import *

urlpatterns = [
    path('', subsmems, name='subsmems'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup', signup, name='signup'), 
    path(
        'login/',
        views.LoginView.as_view(
            authentication_form=UserLoginForm,
        ),
        name='login'
    ), 
    path('deleteJournalEntry', deleteJournalEntry, name='deleteJournalEntry'),
    path('deleteMembershipEntry', deleteMembershipEntry, name='deleteMembershipEntry'), 
    path('table', tablepage, name='tablepage'), 
    path('boardstate', boardstate, name='boardstate'), 
    path('chart', chart, name='chart'), 
    path('del_board_entry', del_board_entry, name='del_board_entry'), 
    path('del_state_entry', del_state_entry, name='del_state_entry'), 
]

subs/models.py
from django.db import models
from datetime import date
from django import forms
from django.contrib.auth.models import User

JOURNAL_NAME_CHOICES = [
    ('NEJM', 'New England Journal of Medicine'),
    ('JVS', 'Journal of Vascular Surgery'),
]

MEMBERSHIP_NAME_CHOICES = [
    ('ACS', 'American College of Surgeons'),
    ('AMA', 'American Medical Association'),
]

CREDIT_FOR_CHOICES = [
    ('ABS', 'American Board of Surgery'),
    ('ABMS', 'American Board of Medical Specialties'),
]

# Create your models here.

class State(models.Model):

    name = models.CharField(
        null=True,
        max_length=1024,
    )

    cycle_length = models.IntegerField(
        null=True,
    )

    cycle_total_cme_req = models.IntegerField(
        null=True,
    )

    cycle_cat_1_req = models.IntegerField(
        null=True,
    )

    cycle_cat_2_req = models.IntegerField(
        null=True,
    )

    email = models.EmailField(
        null=True,
        blank=True,
    )

    def __str__(self): return self.name


class StateEntry(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name="state_entries",
    )

    state = models.ForeignKey(
        State,
        null=True,
        on_delete=models.CASCADE,
        related_name="users",
    )

    first_reg = models.DateField(
        null=True,
        auto_now=False,
        auto_now_add=False
    )

    last_reg = models.DateField(
        null=True,
        auto_now=False,
        auto_now_add=False
    )

    def __str__(self): return self.state.name

class Board(models.Model):

    name = models.CharField(
        null=True,
        max_length=1024,
    )

    cycle_1_length = models.IntegerField(
        null=True,
    )

    cycle_1_total_cme_req = models.IntegerField(
        null=True,
    )

    cycle_1_cat_1_req = models.IntegerField(
        null=True,
    )

    cycle_1_self_req = models.IntegerField(
        null=True,
    )

    cycle_1_cat_2_req = models.IntegerField(
        null=True,
    )

    cycle_2_length = models.IntegerField(
        null=True,
    )

    cycle_2_total_cme_req = models.IntegerField(
        null=True,
    )

    cycle_2_cat_1_req = models.IntegerField(
        null=True,
    )

    cycle_2_self_req = models.IntegerField(
        null=True,
    )

    cycle_2_cat_2_req = models.IntegerField(
        null=True,
    )

    email = models.EmailField(
        null=True,
        blank=True,
    )

    def __str__(self): return self.name



class BoardEntry(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        null=True,
        related_name="board_entries",
    )

    board = models.ForeignKey(
        Board,
        null=True,
        on_delete=models.CASCADE,
        related_name="users",
        )

    first_reg = models.DateField(
        null=True,
         auto_now=False, 
         auto_now_add=False
    )

    last_reg = models.DateField(
        null=True,
         auto_now=False, 
         auto_now_add=False
    )

    timeline_tag = models.CharField(
        null=True,
        max_length=8
    )

    def __str__(self): 
        return self.board.name



class JournalEntry(models.Model):
    name = models.CharField(
        null=False,
        choices=JOURNAL_NAME_CHOICES,
        max_length=256,
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="journals",
        null=True,
    )

    renewal_date = models.DateField(
        verbose_name="Date of Renewal",
        auto_now=False,
        auto_now_add=False,
        blank=True,
        null=True,
    )

    cme_available = models.DateField(
        verbose_name="CME Available",
        auto_now=False,
        auto_now_add=False,
        blank=True,
        null=True,
    )

    sub_cost = models.FloatField(
        blank=True,
        null=False,
        max_length=6,
        verbose_name='Subscription Cost',
    )

    icon_link = models.CharField(
        null=True,
        max_length=1024,
        blank=True)

    credit_for = models.CharField(
        null=True,
        choices=CREDIT_FOR_CHOICES,
        max_length=256)

    def __str__(self):
        return self.name


class MembershipEntry(models.Model):
    name = models.CharField(
        null=False,
        choices=MEMBERSHIP_NAME_CHOICES,
        max_length=256,
    )

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name="memberships",
        null=True,
    )

    renewal_date = models.DateField(
        verbose_name="Date of Renewal",
        auto_now=False,
        auto_now_add=False,
        blank=True,
        null=True,
    )

    cme_available = models.DateField(
        verbose_name="CME Available",
        auto_now=False,
        auto_now_add=False,
        blank=True,
        null=True,
    )

    sub_cost = models.FloatField(
        blank=True,
        null=True,
        max_length=6,
        verbose_name="Subscription Cost",
    )

    icon_link = models.CharField(
        null=True,
        max_length=1024,
        blank=True)

    credit_for = models.CharField(
        null=True,
        choices=CREDIT_FOR_CHOICES,
        max_length=256)

    def __str__(self): return self.name

subs/forms.py
from django import forms
from .models import JournalEntry, MembershipEntry
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.forms import UserCreationForm

class JournalEntryForm(forms.ModelForm):
    """Form definition for JournalEntry."""

    class Meta:
        """Meta definition for JournalEntryform."""

        model = JournalEntry
        fields = ('name','renewal_date', 'sub_cost')
        widgets = {
            'renewal_date': forms.TextInput(attrs={
                'class': 'form-control',
                'style': 'width: 40%; display: inline-block;',
                'placeholder': 'dd/mm/yyyy'
                }),
            'sub_cost': forms.TextInput(attrs={
                'class': 'form-control',
                'style': 'width: 40%; display: inline-block',
                'placeholder': 'eg. 149.99'
            }),
        }


class MembershipEntryForm(forms.ModelForm):
    """Form definition for MembershipEntry."""

    class Meta:
        """Meta definition for MembershipEntryform."""

        model = MembershipEntry
        fields = ('name', 'renewal_date', 'sub_cost')
        widgets = {
            'renewal_date': forms.TextInput(attrs={
                'class': 'form-control',
                'style': 'width: 40%; display: inline-block;',
                'placeholder': 'dd/mm/yyyy'
            }),
            'sub_cost': forms.TextInput(attrs={
                'class': 'form-control',
                'style': 'width: 40%; display: inline-block',
                'placeholder': 'eg. 149.99'
            }),
        }

class UserLoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input100', 
            'placeholder': 'Username',
       }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={ 
            'class': 'input100',
            'placeholder': 'Password',
        }
    ))

class UserSignupForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(UserCreationForm, self).__init__(*args, **kwargs)

    username = forms.CharField(widget=forms.TextInput(
        attrs={
            'class': 'input100',
            'placeholder': 'Username',
        }
    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'input100',
            'placeholder': 'Password',
        }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={
            'class': 'input100',
            'placeholder': 'Confirm Password',
        }
    ))

subs/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from .models import *
from .forms import MembershipEntryForm, JournalEntryForm, UserSignupForm
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.http import JsonResponse
import random
from datetime import date, datetime
from .utils import *


# TODO
# special cme for state: just one time on first cycle depending on dates?
# remind me relevance of expiration dates
# re: annual tab can retrofit
# is None a board choice or a choice of date entry
    # don't make date entry compulsory if it's the latter
 
# Create your views here.
@login_required()
@csrf_exempt 
def chart(request):
    print('obj id is', request.POST['obj_id'])
    obj_id = request.POST['obj_id']
    context = {}
    board_entries, state_entries = BoardEntry.objects.filter(
        user=request.user), StateEntry.objects.filter(user=request.user)
    # check each obj id to see which type of obj and then return 2 lists accodingly for that type of object
    try: 
        eo = BoardEntry.objects.get(pk=obj_id)
        if eo.timeline_tag == '1':
            row_labels = ['Cat I',
                        'Self', 'Cat II']
            row_data = [eo.board.cycle_1_cat_1_req,
                        eo.board.cycle_1_self_req, eo.board.cycle_1_cat_2_req]
        else:
            row_labels = ['Cat I',
                        'Self', 'Cat II']
            row_data = [eo.board.cycle_2_cat_1_req,
                        eo.board.cycle_2_self_req, eo.board.cycle_2_cat_2_req]
    except:
        eo = StateEntry.objects.get(pk=obj_id)
        row_labels = ['Cat I', 'Cat II']
        row_data = [eo.state.cycle_cat_1_req, eo.state.cycle_cat_2_req]
    return JsonResponse(data={
        'labels': row_labels,
        'data': row_data,
    })

@login_required()
def del_board_entry(request):
    BoardEntry.objects.filter(user=request.user, board__name=request.POST['entry_name']).delete()
    print('deleted', request.POST['entry_name'])
    return redirect('boardstate')


@login_required()
def del_state_entry(request):
    StateEntry.objects.filter(user=request.user, state__name=request.POST['entry_name']).delete()
    print('deleted', request.POST['entry_name'])
    return redirect('boardstate')

# add date fields so user can pick f/l date info and store as part of entry
# use f/l to determine cycle credits output on graph
    # if first_reg for board is > board.cycle_1_length, set timeline_tag to 1, else 2
# create state object and populate as counterpoint to ABS
# implement b/s button st approppriate dropdown shown selectively
# add f/l etc func to the state template
# ensure each works fine individually
# try to add annual tab on graph for each
# add multiple graph func for multiple rows being added

@login_required()
def boardstate(request):
    context = {}
    context['board_info'] = Board.objects.all()
    context['state_info'] = State.objects.all()
    if request.method == 'POST':
        name = request.POST.get('name')
        first_reg = datetime.strptime(
            request.POST['first_reg'], '%Y-%m-%d').date()
        last_reg = datetime.strptime(
            request.POST['last_reg'], '%Y-%m-%d').date()
        try:
            board = Board.objects.get(name=name)
            print('board shit')
            b = BoardEntry(board=board, user=request.user,
                           first_reg=first_reg, last_reg=last_reg)
            b.save()
            AssignBoardTimelineTags(request, b, first_reg)
        except:
            state = State.objects.get(name=name)
            print('state shit')
            s = StateEntry(state=state, user=request.user,
                           first_reg=first_reg, last_reg=last_reg)
            s.save()
            print('all state entries are', StateEntry.objects.all())
    board_entries, state_entries = BoardEntry.objects.filter(
        user=request.user), StateEntry.objects.filter(user=request.user)
    context['user_board_entries'], context['user_state_entries'] = board_entries, state_entries
    context['all_user_entries'] = list(board_entries) + list(state_entries)
    # send a combined list for board and state in the order they appear
    # so that you can create many graphs by iterating over that list
    if len(board_entries) == 0 and len(state_entries) == 0:
        context['is_graph'] = False
    else:
        context['is_graph'] = True
    return render(request, 'board.html', context)



@login_required
def subsmems(request):
    user_journal_entries = JournalEntry.objects.filter(user__username=request.user.username)
    user_membership_entries = MembershipEntry.objects.filter(user__username=request.user.username)

    context = {
        'user_journal_entries': user_journal_entries,
        'user_membership_entries': user_membership_entries,
        'current_user_name': request.user.username,
        'journal_form': JournalEntryForm(),
        'membership_form': MembershipEntryForm(),
    }
    if request.method == 'POST':
        # if request was submitted using journalForm buttom
        if 'journalForm' in request.POST:
            # create, check, process data from form, redirect
            context['journal_form'] = JournalEntryForm(request.POST)
            if context['journal_form'].is_valid:
                journalEntry = context['journal_form'].save(commit=False)
                journalEntry.user = request.user
                journalEntry.save()
                return render(request, 'subsmems.html', context) 
        # if request was submitted using memberForm button
        elif 'membershipForm' in request.POST:
            # create, check, process data from form, redirect
            context['membership_form'] = MembershipEntryForm(request.POST)
            if context['membership_form'].is_valid:
                membershipEntry = context['membership_form'].save(commit=False)
                membershipEntry.user = request.user
                membershipEntry.save()
                return render(request, 'subsmems.html', context)

    elif request.method == 'GET':
        return render(request, 'subsmems.html', context)

def signup(request):
    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('subsmems')
    else:
        form = UserSignupForm()
    return render(request, 'signup.html', {'form': form})


@login_required
def deleteJournalEntry(request):
    entry_to_delete = JournalEntry.objects.filter(
        pk=request.POST.get('id'))
    entry_to_delete.delete()    
    return redirect('subsmems')


@login_required
def deleteMembershipEntry(request):
    entry_to_delete = MembershipEntry.objects.filter(
        pk=request.POST.get('id'))
    entry_to_delete.delete()
    return redirect('subsmems')


@login_required
def tablepage(request):
    return render(request, 'tablepage.html') 

subs/templates/signup.html
{% load static %}

<head>
    <title>Signup</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!--===============================================================================================-->	
    <link rel="icon" type="image/png" href="{% static 'subs/login/images/icons/favicon.ico' %}"/>
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'subs/login/vendor/bootstrap/css/bootstrap.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'subs/login/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'subs/login/vendor/animate/animate.css' %}">
<!--===============================================================================================-->	
	<link rel="stylesheet" type="text/css" href="{% static 'subs/login/vendor/css-hamburgers/hamburgers.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'subs/login/vendor/select2/select2.min.css' %}">
<!--===============================================================================================-->
	<link rel="stylesheet" type="text/css" href="{% static 'subs/login/css/util.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'subs/login/css/main.css' %}">
<!--===============================================================================================-->
</head>

<body>
    <div class="limiter">
        <div class="container-login100">
            <div class="wrap-login100">
                <div class="login100-pic js-tilt" data-tilt>
                    <img src="{% static 'subs/login/images/img-01.png' %}" alt="IMG">
                </div>

                <form class="login100-form" method="post" action="{% url 'signup' %}">
                    {% csrf_token %}
                    <span class="login100-form-title">
                        MyConCert Sign Up
                    </span>

                        {% for field in form %}
                        <div class="wrap-input100 form-group">
                            {{ field }}
                            {% if field.errors %}
                            <br>
                            <small style="color: grey">{{ field.help_text }}</small>
                            {% endif %}
                            {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                            {% endfor %}
                        </div>
                        {% endfor %}

                    <div class="container-login100-form-btn">
                        <input type="submit" value="Sign Up" class="login100-form-btn">
                        <input type="hidden" name="next" value="{{ next }}">
                    </div>

                    <div class="text-center p-t-12">
                        <a class="txt2" href="{% url 'password_reset' %}">
                            Forgot Password?
                        </a>
                    </div>

                    <div class="text-center p-t-136">
                        <a class="txt2" href="{% url 'login' %}">
                            Returning User? Login.
                            <i class="fa fa-long-arrow-right m-l-5" aria-hidden="true"></i>
                        </a>
                    </div>
                </form>
            </div>
        </div>
    </div>

<!--===============================================================================================-->	
	<script src="{% static 'subs/login/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'subs/login/vendor/bootstrap/js/popper.js' %}"></script>
	<script src="{% static 'subs/login/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'subs/login/vendor/select2/select2.min.js' %}"></script>
<!--===============================================================================================-->
	<script src="{% static 'subs/login/vendor/tilt/tilt.jquery.min.js' %}"></script>
	<script >
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>

</body>

subs/templates/subsmems.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <title>MyConcert</title>
    <style>
      #test {
        -webkit-animation: fadein 3s; /* Safari, Chrome and Opera > 12.1 */
        -moz-animation: fadein 3s; /* Firefox < 16 */
        -ms-animation: fadein 3s; /* Internet Explorer */
        -o-animation: fadein 3s; /* Opera < 12.1 */
        animation: fadein 3s;
      }

      @keyframes fadein {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }

      /* Firefox < 16 */
      @-moz-keyframes fadein {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }

      /* Safari, Chrome and Opera > 12.1 */
      @-webkit-keyframes fadein {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }

      /* Internet Explorer */
      @-ms-keyframes fadein {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }

      /* Opera < 12.1 */
      @-o-keyframes fadein {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }
    </style>
  </head>

  <body>
    <div>
      <div style="padding-bottom: 25px; width: 100%;">
        <div style="width: 10%; padding-top: 35px; float: right;">
          <!-- Welcome to the future of medicine, {{ current_user_name }}  -->
          <a href="{% url 'logout' %}">
            <input type="submit" value="Logout" class="btn btn-primary" />
          </a>
        </div>

        <div style="width: 10%; padding-top: 35px; float: right;">
          <a href="{% url 'boardstate' %}">
            <input type="submit" value="Board & State" class="btn btn-primary" />
          </a>
        </div>

        <div style="padding: 20px; float: left;" class="display-4" id="test">
          Welcome to the future of medicine, {{ current_user_name }}
        </div>
      </div>
    </div>

    <div>
      <div>
        <div
          style="width: 50%; padding-left: 50px; float: left; display: block;"
        >
          <div
            style="
              width: 90%;
              border: 1px solid;
              border-radius: 2.5%/5%;
              padding: 30px;
            "
          >
            <form
              action="{% url 'subsmems' %}"
              method="post"
              style="text-align: center;"
            >
              {% csrf_token %}
              <div class="form-group">
                {{ journal_form.as_p }}
              </div>
              <input
                type="submit"
                name="journalForm"
                value="Add Journal"
                class="btn btn-primary"
              />
            </form>
          </div>
        </div>

        <div
          style="width: 50%; padding-left: 50px; float: right; display: block;"
        >
          <div
            style="
              width: 90%;
              border: 1px solid;
              border-radius: 2.5%/5%;
              padding: 30px;
            "
          >
            <form
              action="{% url 'subsmems' %}"
              method="post"
              style="text-align: center;"
            >
              {% csrf_token %}
              <div class="form-group">
                {{ membership_form.as_p }}
              </div>
              <input
                type="submit"
                name="membershipForm"
                value="Add Membership"
                class="btn btn-primary"
              />
            </form>
          </div>
        </div>
      </div>

      <div style="width: 100%; padding-top: 30px; display: inline-block;">
        <ul>
          {% if user_journal_entries %} {% for entry in user_journal_entries %}

          <div
            class="jumbotron"
            style="
              width: 95%;
              padding: 20px 20px 20px 20px;
              height: 18rem;
              border-radius: 1%/5%;
            "
          >
            <h1 class="display-6">{{ entry.get_name_display }}</h1>
            <p class="lead">Subscription Cost: ${{ entry.sub_cost }}</p>
            <hr class="my-4" />
            <p>Due for renewal on {{ entry.renewal_date }}</p>
            <form action="{% url 'deleteJournalEntry' %}" method="POST">
              {% csrf_token %}
              <button
                type="submit"
                value="{{ entry.id }}"
                name="id"
                class="btn btn-primary"
                placeholder="Delete Entry"
              >
                Delete Entry
              </button>
            </form>
          </div>
          {% endfor %} {% endif %} {% if user_membership_entries %} 
          {% for entry in user_membership_entries %}
          <div
            class="jumbotron"
            style="
              width: 95%;
              padding: 20px 20px 20px 20px;
              height: 18rem;
              border-radius: 1%/5%;
            "
          >
            <h1 class="display-6">{{ entry.get_name_display }}</h1>
            <p class="lead">Subscription Cost: ${{ entry.sub_cost }}</p>
            <hr class="my-4" />
            <p>Due for renewal on {{ entry.renewal_date }}</p>

            <form action="{% url 'deleteMembershipEntry' %}" method="POST">
              {% csrf_token %}
              <button
                type="submit"
                value="{{ entry.id }}"
                name="id"
                class="btn btn-primary"
                placeholder="Delete Entry"
              >
                Delete Entry
              </button>
            </form>
          </div>
          {% endfor %} {% endif %}
        </ul>
      </div>
    </div>
  </body>
</html>